### ISSUE TITLE
Move to parameter in I2C?

### ISSUE THREAD

**Issue by fsantanna** [ceu-arduino/driver-i2c#1]
https://github.com/ceu-arduino/driver-i2c/blob/1b5ba09248a116c8e91bd58dea8ed86777a1caa0/i2c.ceu#L4

This could be an optional argument to `I2C`:

```
input (on/off, u8?) I2C;
```

**Comment by fsantanna** [comment]
If possible, include the commit that closes the issue.
(Or close from the commit itself: https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by mnaveenkumar2009** [comment]
Commit 5e3209be fixes the issue.

Will close with the commit from next time
