### ISSUE TITLE
Is variable `deviceAddress` needed?

### ISSUE THREAD

**Issue by fsantanna** [ceu-arduino/driver-i2c#2]
https://github.com/ceu-arduino/driver-i2c/blob/5e3209bebf471a34c957160e9892bcedc40908c2/avr/i2c.ceu#L26

**Comment by mnaveenkumar2009** [comment]
Not required and hence removed, If required in future it can be obtained by TWAR>>1 .. it is also used in the API the same way to know whether it is the master or slave.

dfb8f8b fixes this issue.
